name: the_streets
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.0.5
  animated_splash_screen: ^1.3.0
  intl: ^0.17.0
#  firebase_storage: ^11.0.8
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
    # switch animation between light and dark theme
  animated_theme_switcher: ^2.0.1-nullsafety.0
  provider:
  firebase_storage: ^11.0.8
  marquee: ^2.2.3
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^10.2.0
  simple_animations: ^5.0.0+3
  path: ^1.8.2

#  widget_loading: ^0.3.2
#  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/users/